version: '4'
services:
  mongo-db:
    image: mongo:noble
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=product-service


    networks:
      - app-network
    volumes:
      - ./mongo-volume:/data/db

networks:
  app-network:
    driver: bridge