version: "5"
services:
  inventory-mysql:
    image: mysql:9.2
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory-service
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql